RealEstate/Controllers/ListingDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RealEstateRentals.BusinessLogic;
using RealEstateRentals.ViewModels;  

namespace RealEstateRentals.Controllers
{
    public class ListingDetailController : Controller
    {
        //
        // GET: /ListingDetail/

        public ActionResult Index(int ListingID)
        {
            ListingDetailsBL oLDBL = new ListingDetailsBL();
            ListingInformationVM oLIVM = oLDBL.GetListingInformation(ListingID);
            return View(oLIVM);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(FormCollection myCollection)
        {
            return View();
        }

        public ActionResult Update()
        {
            return View();
        }
        public ActionResult Delete()
        {
            return View();
        }

    }
}

RealEstate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8" />
    <title>@ViewBag.Title – Mobile Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
     @Styles.Render("~/Content/Mobilecss")
    @Scripts.Render("~/bundles/Mobilejs")
   <meta name="viewport" content="width=device-width, initial-scale=1" />
        </head>
        <body>
             <div data-role="page" data-theme="a">
    <div data-role="header" data-position="fixed" data-theme="b">
        <div data-role="navbar" data-theme="a" data-iconpos="top">
            <ul>
                <li><a href="@Url.Action("Index", "Home")" data-icon="home">Home</a></li>
                <li><a href="@Url.Action("Add",  "ListingDetail")" data-icon="check">Add Listing</a></li>                    
            </ul>
        </div>
    </div>
    <div data-role="content">
            
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
         </div>
                 
</div>
        </body>
    </html>